# Generated by Django 5.2.6 on 2025-09-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('identificador_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('foto_ine', models.ImageField(blank=True, null=True, upload_to='ines/')),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas/')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='Contrato de servicio', max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='contratos_pdf/')),
                ('excel', models.FileField(blank=True, null=True, upload_to='contratos_xlsx/')),
                ('datos', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.clientelocal')),
            ],
        ),
    ]
