# Generated by Django 5.2.6 on 2025-11-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='html_contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
